# tox (https://tox.readthedocs.io/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. Run it with
# "uv run tox -p" (or "make test-all").

[tox]
envlist = py312, py313, py314

[testenv]
runner = uv-venv-lock-runner
extras = test
commands =
    pytest -rx
