# Do not edit this file. It was auto-generated from the
# corresponding YAML file.
spec = {
    "base": "ISO3",
    "options": ["eu", "unfccc", "groups", "historical", "kosovo", "gcam", "pse_in_isr"],
    "unsupported": [
        {
            "options": ["gcam", "pse_in_isr"],
            "comment": "the GCAM regions have PSE separately",
        }
    ],
    "aliases": {
        "ISO3_PRIMAP": ["eu", "groups", "historical", "pse_in_isr", "unfccc"],
        "ISO3_GCAM": ["eu", "gcam", "groups", "historical", "kosovo", "unfccc"],
    },
}
